name: Auto Merge PRs

on:
  pull_request:

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR
        uses: actions/checkout@v2

      - name: Check PR Conditions
        run: |
          # Ensure the PR meets specific conditions
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Check if there are no deletions in the PR
          if [[ $(git diff --stat origin/main...HEAD | grep -E '(\s\||\|)' | awk -F '|' '{print $1}' | sed -e 's/ //g') == "0" ]]; then
            # Check if additions are from a single new file inside the "names" folder
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
            if [[ $(echo "$CHANGED_FILES" | wc -l) == "1" && $(echo "$CHANGED_FILES" | grep "^names/") ]]; then
              echo "All conditions met. Merging PR #$PR_NUMBER"
              git config --global user.email "bot@github.com"
              git config --global user.name "Bot"
              git fetch origin refs/pull/$PR_NUMBER/merge
              git merge FETCH_HEAD -m "Auto-merged PR #$PR_NUMBER"
              git push origin HEAD
            else
              echo "Conditions not met. PR cannot be merged."
            fi
          else
            echo "Conditions not met. PR cannot be merged."
          fi
