name: Generate and Deploy Index.html

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate Index.html
        run: |
          echo "<html><head><title>File List</title></head><body>" > index.html
          echo "<style>table { width: 100%; border-collapse: collapse; } th, td { border: 1px solid #dddddd; text-align: left; padding: 8px; } th { background-color: #f2f2f2; }</style>" >> index.html
          echo "<table><tr><th>Time</th><th>Filename</th><th>Content</th></tr>" >> index.html
          for file in $(ls -rt names/*); do
            filename=$(basename "$file")
            content=$(cat "$file")
            modification_time=$(stat -c %Y "$file")
            echo "<tr><td>$(date -d @$modification_time)</td><td>$filename</td><td>$content</td></tr>" >> index.html
          done
          echo "</table></body></html>" >> index.html

      - name: Commit and Push
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"
          git add index.html
          git commit -m "Auto-generate index.html"
          git push
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
