name: Generate and Push Index.html

on:
  push:
    branches:
      - main

jobs:
  generate_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate Index.html
        run: |
          echo "<html><head><title>File List</title></head><body>" > index.html
          echo "<style>table { width: 100%; border-collapse: collapse; } th, td { border: 1px solid #dddddd; text-align: left; padding: 8px; } th { background-color: #f2f2f2; }</style>" >> index.html
          echo "<table><tr><th>File Name</th><th>Content</th></tr>" >> index.html
          for file in names/*; do
            filename=$(basename "$file")
            content=$(cat "$file")
            echo "<tr><td>$filename</td><td>$content</td></tr>" >> index.html
          done
          echo "</table></body></html>" >> index.html

      - name: Commit and Push
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"
          git add index.html
          git commit -m "Auto-generate index.html"
          git push
